# Generated by Django 5.0.4 on 2024-04-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_new_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ManyToManyField(related_name='new_category', to='news.category', verbose_name='Категория'),
        ),
    ]
